apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "aphros.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "aphros.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "aphros.selectorLabels" . | nindent 6}}
  serviceName: {{ include "aphros.fullname" . }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      name: {{ include "aphros.fullname" . }}
      labels: {{ include "aphros.labels" . | nindent 8 }}
    spec:
      initContainers:
      - name: {{ include "aphros.fullname" . }}-config-init
        image: busybox 
        imagePullPolicy: IfNotPresent 
        command:
          - /bin/sh
          - -c
          - |-
            ID=$(echo $HOSTNAME | rev | cut -d- -f1 | rev)
            cat > /var/run/aphros/config.yaml <<EOD
            data-dir: /var/run/aphros/data
            bind-addr: "$HOSTNAME.aphros.{{.Release.Namespace}}.svc.cluster.local:{{.Values.serfPort}}"
            bootstrap: $([ $ID = 0 ] && echo true || echo false)
            $([ $ID != 0 ] && echo "start-join-addrs: \"aphros-0.aphros.{{.Release.Namespace}}.svc.cluster.local:{{.Values.serfPort}}\"")
            EOD
        volumeMounts:
        - name: datadir
          mountPath: /var/run/aphros
      containers:
      - name: {{ include "aphros.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.rpcPort }}
          name: rpc
        - containerPort: {{ .Values.serfPort }}
          name: serf
        args:
          - --config-file=/var/run/aphros/config.yaml
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |-
              /bin/grpc_health_probe -addr=$HOSTNAME.aphros.{{.Release.Namespace}}.svc.cluster.local:{{.Values.rpcPort}}
          initialDelaySeconds: 10
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |-
              /bin/grpc_health_probe -addr=$HOSTNAME.aphros.{{.Release.Namespace}}.svc.cluster.local:{{.Values.rpcPort}}
          initialDelaySeconds: 10
        volumeMounts:
        - name: datadir
          mountPath: /var/run/aphros
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ] 
      resources:
        requests:
          storage: {{ .Values.storage }}